### PR TITLE
remove unused import

### PR DESCRIPTION
**Pull request by mayelena**

### CODE REVIEW

**Comment by mayelena** [comment]
recheck

**Comment by imbajin** [comment]
Thanks, sign this then `recheck`

image

**Comment by mayelena** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mayelena** [comment]
recheck

**Review by javeme — APPROVED** [review]
Congratulations on your first contribution, thank you.

**Review by imbajin — APPROVED** [review]

**Pull request merged**
