### PR TITLE
inexplicit parameter name bug fixed https://github.com/hugegraph/huge…

### LINKED ISSUE #519: 0.9.2 中关于kneighbor和kout 参数max_depth的报错不明确，易混淆
另外在092 release notes中，没有明确提及参数名由depth升级到max_depth

image

### PR DESCRIPTION
**Pull request by oushu1zhangxiangxuan1**
fixed #519

### CODE REVIEW

**Comment by javeme** [comment]
Good improvement, thanks!

Could you update commit message like this:
```
fixed bug: implicit parameter name 

fixed #519
```
Note the blank line in the middle and update the pull-request title at the same time.

**Comment by javeme** [comment]
@oushu1zhangxiangxuan1 
Since you haven't updated for a long time, I have already committed it https://github.com/hugegraph/hugegraph/pull/563 for you (you are still the author).

**Comment by oushu1zhangxiangxuan1** [comment]
@javeme oh I'm sorry，I've been busy on my working these days

**Comment by javeme** [comment]
It's ok, look forward your further contributions.

ps. @Github seems to have a bug, the author has been changed to me after merged, I have already fedback this question to them.

**Comment by javeme** [comment]
@oushu1zhangxiangxuan1 Regarding the change of author information, Github's response is as follows, apologies for for it.
image

**Comment by oushu1zhangxiangxuan1** [comment]
@javeme It's ok dude.  By the way, I'm migrating my Github account to https://github.com/John-Saxon

> @oushu1zhangxiangxuan1 Regarding the change of author information, Github's response is as follows, apologies for for it. image

**Pull request closed without merging**
