### PR TITLE
Fix gremlin-console can't work

### LINKED ISSUE #1026: 有没有功能支持，输入gremlin语句的文本，解析后操作hugegraph，返回结果
输入文本g.V().hasLabel('person').out().has('name',within('vadas','josh'))
返回查询到的数据，就像在控制台操作一样

### PR DESCRIPTION
**Pull request by Linary**
Fix #1026

Change-Id: Ice222d809e4161f1d4d1f04822bef1c5af380a10

### CODE REVIEW

**Comment by javeme** [comment]
run with memory backend:
```sh
$ hugegraph-0.11.1/bin/gremlin-console.sh 
objc[8740]: Class JavaLaunchHelper is implemented in both /bin/java and  /jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: HugeGraph
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> graph = HugeFactory.open("hugegraph-0.11.1/conf/hugegraph.properties")
==>standardhugegraph[hugegraph]
gremlin> g=graph.traversal()
==>graphtraversalsource[standardhugegraph[hugegraph], standard]
gremlin> g.V()
main dict load finished, time elapsed 1268 ms
model load finished, time elapsed 73 ms.
gremlin> graph.schema().vertexLabel('person').useCustomizeStringId().create();graph.schema().edgeLabel('next').sourceLabel('person').targetLabel('person').create(); g.addV('person').property(id,'A').as('a').addV('person').property(id,'B').as('b').addV('person').property(id,'C').as('c').addV('person').property(id,'D').as('d').addV('person').property(id,'E').as('e').addV('person').property(id,'F').as('f').addE('next').from('a').to('b').addE('next').from('b').to('c').addE('next').from('b').to('d').addE('next').from('c').to('d').addE('next').from('c').to('e').addE('next').from('d').to('e').addE('next').from('e').to('f').addE('next').from('f').to('d')
==>e[SF>1>>SD][F-next->D]
gremlin> g.V()
==>v[A]
==>v[B]
==>v[C]
==>v[D]
==>v[E]
==>v[F]
```

register with ` com.baidu.hugegraph.dist.RegisterUtil.registerRocksDB() ` for rocksdb backend.

**Comment by javeme** [comment]
run remote with error:
```sh
gremlin> :remote connect tinkerpop.server hugegraph-0.11.1/conf/remote.yaml 
==>Configured localhost/127.0.0.1:8182
gremlin> :> g.V().count()
Index: 121, Size: 0
```
image

**Comment by Linary** [comment]
remote.yaml
```
hosts: [localhost]
port: 8182
serializer: {
  className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0,
  config: {
    serializeResultToString: true,
    ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
  }
}
```

```
gremlin>  :remote connect tinkerpop.server conf/remote.yaml
==>Configured localhost/127.0.0.1:8182
gremlin> :> g.V()
==>v[1]
==>v[2]
==>v[3]
==>v[4]
==>v[5]
==>v[6]
gremlin> :> g.V().count()
==>6
```

**Comment by Linary** [comment]
remote.yaml
```
hosts: [localhost]
port: 8182
serializer: {
  className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0,
  config: {
    serializeResultToString: false,
    ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
  }
}
```

```
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Configured localhost/127.0.0.1:8182
gremlin> :> hugegraph.traversal().V()
==>[id:1:1,label:person,type:vertex,properties:[name:1,city:H]]
==>[id:1:2,label:person,type:vertex,properties:[name:2,city:H]]
==>[id:2:lop,label:software,type:vertex,properties:[name:lop,lang:java,price:328]]
==>[id:1:josh,label:person,type:vertex,properties:[name:josh,age:32,city:Beijing]]
==>[id:1:marko,label:person,type:vertex,properties:[name:marko,age:29,city:Beijing]]
==>[id:1:peter,label:person,type:vertex,properties:[name:peter,age:35,city:Shanghai]]
==>[id:1:vadas,label:person,type:vertex,properties:[name:vadas,age:27,city:Hongkong]]
==>[id:2:ripple,label:software,type:vertex,properties:[name:ripple,lang:java,price:199]]
```

**Comment by 1436516871** [comment]
### 连接远程的server，提交gremlin语句
修改remote.yaml
```
hosts: [localhost]
port: 8182
serializer: {
  className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0,
  config: {
    serializeResultToString: false,
    ioRegistries: [com.baidu.hugegraph.io.HugeGraphIoRegistry]
  }
}
```
启动HugeGraphServer
进入gremlin控制台
```
[~]$ ./bin/gremlin-console.sh

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: HugeGraph
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
```

```
gremlin> :> hugegraph.schema().vertexLabel('person').useCustomizeStringId().create();hugegraph.schema().edgeLabel('next').sourceLabel('person').targetLabel('person').create();hugegraph.traversal().addV('person').property(id,'A').as('a').addV('person').property(id,'B').as('b').addV('person').property(id,'C').as('c').addV('person').property(id,'D').as('d').addV('person').property(id,'E').as('e').addV('person').property(id,'F').as('f').addE('next').from('a').to('b').addE('next').from('b').to('c').addE('next').from('b').to('d').addE('next').from('c').to('d').addE('next').from('c').to('e').addE('next').from('d').to('e').addE('next').from('e').to('f').addE('next').from('f').to('d')
==>[id:SF>1>>SD,label:next,type:edge,outV:F,outVLabel:person,inV:D,inVLabel:person,properties:[]]
```

```
gremlin> :> hugegraph.traversal().V()
==>[id:A,label:person,type:vertex,properties:[]]
==>[id:B,label:person,type:vertex,properties:[]]
==>[id:C,label:person,type:vertex,properties:[]]
==>[id:D,label:person,type:vertex,properties:[]]
==>[id:E,label:person,type:vertex,properties:[]]
==>[id:F,label:person,type:vertex,properties:[]]
gremlin> :> hugegraph.traversal().E()
==>[id:SA>1>>SB,label:next,type:edge,outV:A,outVLabel:person,inV:B,inVLabel:person,properties:[]]
==>[id:SB>1>>SC,label:next,type:edge,outV:B,outVLabel:person,inV:C,inVLabel:person,properties:[]]
==>[id:SB>1>>SD,label:next,type:edge,outV:B,outVLabel:person,inV:D,inVLabel:person,properties:[]]
==>[id:SC>1>>SD,label:next,type:edge,outV:C,outVLabel:person,inV:D,inVLabel:person,properties:[]]
==>[id:SC>1>>SE,label:next,type:edge,outV:C,outVLabel:person,inV:E,inVLabel:person,properties:[]]
==>[id:SD>1>>SE,label:next,type:edge,outV:D,outVLabel:person,inV:E,inVLabel:person,properties:[]]
==>[id:SE>1>>SF,label:next,type:edge,outV:E,outVLabel:person,inV:F,inVLabel:person,properties:[]]
==>[id:SF>1>>SD,label:next,type:edge,outV:F,outVLabel:person,inV:D,inVLabel:person,properties:[]]
gremlin> :> hugegraph.traversal().E().count()
==>8
gremlin> :> hugegraph.traversal().V().count()
==>6
```

**Comment by 1436516871** [comment]
### Accessing local data in console
Enter the gremlin console
```
[~]$ ./bin/gremlin-console.sh

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: HugeGraph
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
```
Register the backend and serializer of rocksdb
```
gremlin> com.baidu.hugegraph.dist.RegisterUtil.registerRocksDB()
==>null
```
Create graph instance
```
gremlin> graph = HugeFactory.open("conf/hugegraph.properties")
==>standardhugegraph[hugegraph]
```
```
gremlin> g=graph.traversal()
==>graphtraversalsource[standardhugegraph[hugegraph], standard]
Execute statement
gremlin> g.V()
main dict load finished, time elapsed 959 ms
model load finished, time elapsed 58 ms.
==>v[A]
==>v[B]
==>v[C]
==>v[D]
==>v[E]
==>v[F]
```

**Comment by javeme** [comment]
image
```
gremlin> g.V().has('name','marko').out('knows').values('name')
org.apache.tinkerpop.gremlin.process.traversal.step.util.HasContainer.testAll(Lorg/apache/tinkerpop/gremlin/structure/Element;Ljava/util/List;)Z
```

**Comment by 1436516871** [comment]
It can be used normally but not reproduced
image

**Pull request merged**
